### PR TITLE
Challenge complete

### PR DESCRIPTION
**Pull request by bsmall512**
Moe - 
I think this is what you're looking for. Using the bulk method rather than the index method on line 20 decreased the indexing rate significantly. Fun challenge! I hope to talk to you again soon.
Thanks, 
Brian Small

### CODE REVIEW

**Comment by mistermoe** [comment]
Hey @bsmall512, I ran your solution and ran into an error. Here's all the output so you can get some context as to where the error is occuring:

```
root@2f579f9f4888:/code# node solution.js
deleting records index
creating records index
flushing redis
0 records seeded in redis
1000 records seeded in redis
2000 records seeded in redis
3000 records seeded in redis
4000 records seeded in redis
5000 records seeded in redis
6000 records seeded in redis
7000 records seeded in redis
8000 records seeded in redis
9000 records seeded in redis
done seeding redis
importing records from redis -> elasticsearch
(node:36) UnhandledPromiseRejectionWarning: Error: [illegal_argument_exception] Malformed action/metadata line [1], expected START_OBJECT or END_OBJECT but found [START_ARRAY]
    at respond (/code/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/code/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/code/node_modules/elasticsearch/src/lib/connectors/http.js:165:7)
    at IncomingMessage.wrapper (/code/node_modules/lodash/lodash.js:4949:19)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:36) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bsmall512** [comment]
@mistermoe That error was occurring when I ran baseline.js. Do you get it as well?

**Comment by bsmall512** [comment]
@mistermoe I'm sorry, you're right... The code shipped with a different error. I will push another commit shortly.

**Comment by mistermoe** [comment]
no worries

**Comment by mistermoe** [comment]
@bsmall512 i went ahead and fixed the error you ran into in `baseline.js`. Feel free to sync your fork. Instructions for that are [here](https://help.github.com/articles/syncing-a-fork/)

**Pull request closed without merging**
